--- !ruby/object:Claret::Project 
items: 
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 1
  name: Figure out a good way to configuration
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 2
  name: Set up a fake web server to test the rest client/parsing
name: Gliffy Ruby API
next_id: 3
