require 'rake/clean'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rcov/rcovtask'
require 'rubygems'
require 'rake/gempackagetask'
require 'sdoc'

begin
  $: << '../grancher/lib'
  require 'grancher/task'

  Grancher::Task.new do |g|
    g.branch = 'gh-pages'
    g.push_to = 'origin'
    g.directory 'html'
  end
rescue
  puts "cd ../ ; git clone git://github.com/judofyr/grancher.git"
  puts "if you want to manage the GitHub Pages page"
end

Rake::RDocTask.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include("README.rdoc","lib/**/*.rb","bin/**/*")
  rd.options << '--fmt' << 'shtml'
  rd.template = 'direct'
  rd.title = 'Ruby Client for Gliffy'
end

spec = eval(File.read('gliffy.gemspec'))
 
Rake::GemPackageTask.new(spec) do |pkg|
end

{ :test => { :desc => 'Runs Unit Tests', :prefix => 'tc_', :required_file => nil, :coverage => true },
  :inttest => { :desc => 'Runs Integration Tests', :prefix => 'int_', :required_file => 'it_cred.rb', :coverage => true },
  :functest => { :desc => 'Runs Functional Tests', :prefix => 'func_', :required_file => 'functest_cred.rb', :coverage => true },
  :alltest => { :desc => 'Runs All Tests at Once', :prefix => '', :required_file => 'functest_cred.rb', :coverage => true },
  :setup_account => { :desc => 'Sets up a Test Account', :prefix => 'setup_', :required_file => 'it_cred.rb', :coverage => false },
}.each do |test_name,test_info|
  if test_info[:required_file] && !File.exists?('test/' + test_info[:required_file])
    task test_name do
      $stderr.puts "you need to create test/#{test_info[:required_file]} to run these tests"
      $stderr.puts "See the documentation for what this should look like"
    end
  else
    desc test_info[:desc]
    Rake::TestTask.new(test_name) do |t|
      t.libs << 'lib'
      t.libs << 'test'
      t.libs << 'ext'
      t.test_files = FileList['test/' + test_info[:prefix] + '*.rb']
    end
    if test_info[:coverage]
      Rcov::RcovTask.new(('rcov_' + test_name.to_s).to_sym) do |t|
        t.libs << 'lib'
        t.libs << 'test'
        t.libs << 'ext'
        t.test_files = FileList['test/' + test_info[:prefix] + '*.rb']
      end
    end
  end
end

task :clobber_coverage do
    rm_rf "coverage"
end

task :default => :test

task :publish_rdoc => [:rdoc,:publish]

task :update_version do 
  File.open('lib/gliffy/version.rb','w') do |file|
    file.puts "# Generated by rake update_version"
    file.puts "module Gliffy"
    file.puts "  GLIFFY_VERSION = '#{spec.version}'"
    file.puts "end"
  end
end

task :bamboo => [:setup_account, :functest]
